### ISSUE TITLE
User creations support ceph rgw

### ISSUE THREAD

**Issue by daanvinken** [linode/provider-ceph#50]
Hi!
Just a quick question - Really like this provider and it's very slim. 
Are you guys open to adding S3 user creation to this project for ceph rgw? I might be able to find some time for this.

If so, I'll will write up a longer ticket about requirements etc if you like.

Cheers,
Daan

**Comment by nolancon** [comment]
Hi @daanvinken 
We are open to any and all contributions :smile:  feel free to write up a ticket :+1:

**Comment by daanvinken** [comment]
Ok, do you guys use a slack channel of some sort? We'd need to restructure the apis a little bit. Because everything falls under ceph-provider right now. I thikn we should split that up.
<img width="491" alt="Screenshot 2023-09-08 at 10 54 24" src="https://github.com/linode/provider-ceph/assets/47114744/edf11f94-6e05-49c9-8ba1-e9d1db1ebc64">

<img width="470" alt="Screenshot 2023-09-08 at 10 55 13" src="https://github.com/linode/provider-ceph/assets/47114744/56714d9b-0bce-4a05-8f3f-f532d94dcfde">

**Comment by nolancon** [comment]
I have just created a channel #provider-ceph in the Crossplane slack workspace, feel free to join.
